apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: default
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      hostNetwork: true
      containers:
        - name: todo
          image: docker.io/library/node:alpine
          workingDir: /app
          command:
            - npm
            - start
          containerPort: 8080
          env:
            - name: DATA_FILE
              value: /app/data.json
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          hostPath:
            path: ./
